name: Deploy to Cloudflare

on:
  push:
    branches:
      - main  # Triggers when pushing to main branch
  workflow_dispatch:  # Allows manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare
        run: npx wrangler publish
